const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
const panel=document.createElement('div');panel.className='tempo-panel';panel.innerHTML='<div><label for="visual-tempo">Tempo visuale <output id="tempo-value">180 BPM</output></label><span>Regola la luce al ritmo del set.</span></div><div class="tempo-controls"><input id="visual-tempo" type="range" min="90" max="200" step="1" value="180" aria-label="Tempo visuale in BPM"><button id="tempo-tap" aria-label="Batti il tempo della musica">Tap</button></div>';
document.querySelector('.player-actions')?.after(panel);
const slider=panel.querySelector<HTMLInputElement>('input')!,output=panel.querySelector('output')!;let bpm=180,playing=false,position=0,sampled=performance.now(),raf=0,last=0;const taps:number[]=[];
function update(value:number){bpm=Math.max(90,Math.min(200,value));slider.value=String(bpm);output.value=bpm+' BPM';document.documentElement.style.setProperty('--beat-duration',60/bpm+'s')}
slider.addEventListener('input',()=>update(Number(slider.value)));panel.querySelector('button')!.addEventListener('click',()=>{const now=performance.now();if(taps.length&&now-taps[taps.length-1]>1800)taps.length=0;taps.push(now);if(taps.length>6)taps.shift();if(taps.length>1)update(Math.round(60000/((now-taps[0])/(taps.length-1))))});
function frame(now:number){raf=0;if(document.hidden||reduce||!playing)return;if(now-last>32){last=now;const elapsed=position+now-sampled;const phase=(elapsed/60000*bpm)%1;const pulse=Math.exp(-phase*9);document.documentElement.style.setProperty('--light-pulse',pulse.toFixed(3));window.dispatchEvent(new CustomEvent('kist:pulse',{detail:{pulse,phase,bpm}}))}raf=requestAnimationFrame(frame)}
window.addEventListener('kist:audio',e=>{const d=(e as CustomEvent<{playing:boolean;position?:number}>).detail;const now=performance.now();if(d.position!==undefined)position=d.position;else if(playing)position+=now-sampled;sampled=now;playing=d.playing;document.body.classList.toggle('sound-active',playing);if(!playing){cancelAnimationFrame(raf);raf=0;document.documentElement.style.setProperty('--light-pulse','0')}else if(!raf&&!reduce)raf=requestAnimationFrame(frame)});
document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else if(playing&&!raf&&!reduce)raf=requestAnimationFrame(frame)});update(bpm);
export {};
